<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
			form {
				color: #719e40;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 30px;
                font-weight: 200;
                margin-bottom: 0;
			}
        </style>
    </head>
    <body>
	
		
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

		<form action="/shorten" method="post">
		  Long Url: <input type="text" name="lurl"><br>
		  Service:  <select name=provider>
			  <option value=""></option>
			  <option value="bitgiabit">bit.li</option>
			</select><br>
		  <input type="submit" value="Submit">
		</form>
		
		<?php if (isset($shorten)) : ?>
            <h2>Hello <?= htmlspecialchars($shorten); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
    </body>
</html>
